@apiUrl = http://localhost:5000

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmMjdhZTI0OS1jMjBkLTQ3MTAtYWVmNi1jYWNmMjhiOWNkMTQiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJpYXQiOjE1NTE3Mzc2MTYsImV4cCI6MTU1MTczNzkxNiwidW5pcXVlX25hbWUiOiJmMjdhZTI0OS1jMjBkLTQ3MTAtYWVmNi1jYWNmMjhiOWNkMTQifQ.x4chSpANhIJbNrBMXKlf8qih1NbJpH5Y2K2sSYWDTdk

### ================= CREATE USER ======================= #

POST {{apiUrl}}/api/users/register
content-type: application/json

{
    "Login": "2marca",
    "Firstname": "marzec2",
    "Email": "marzec2@op.pl",
    "Password": "2marca"
}

### ================= LOGIN USER ======================= #

POST {{apiUrl}}/api/users/login
content-type: application/json

{
    "Login": "2marca",
    "Password": "2marca"
}




### ================= GET FOOD ITEMS ======================= #

GET {{apiUrl}}/api/FoodItems
authorization: Bearer {{accessToken}}
content-type: application/json

### ================= GET FOOD ITEM BY ID ======================= #

@userId = C497ED62-3944-4F09-85E0-D99459A841E6
GET {{apiUrl}}/api/FoodItems/{{userId}}
authorization: Bearer {{accessToken}}
content-type: application/json

### ================= CREATE FOOD ITEMS ======================= #

POST {{apiUrl}}/api/FoodItems
authorization: Bearer {{accessToken}}
content-type: application/json

{
    "Name": "piwo",
    "Weight": 1,
    "Quantity": 22,
    "CategoryId": 2
}






#### ================= Get all recipes ======================= #

GET {{apiUrl}}/api/Recipes
authorization: Bearer {{accessToken}}
content-type: application/json

#### ================= Get recipe details ======================= #

@recipeGuid = e198f1db-4898-4c62-a34a-a182a17ddb9f

GET {{apiUrl}}/api/Recipes/{{recipeGuid}}
authorization: Bearer {{accessToken}}
content-type: application/json

#### ================= CREATE RECIPES ======================= #

POST {{apiUrl}}/api/Recipes
authorization: Bearer {{accessToken}}
content-type: application/json

{
    "Name": "2marzec",
    "Description": "siema marzec",
    "Ingredients": 
	[
		{"Name": "New", "Weight": "150"},
		{"Name": "ziemniak", "Weight": "160"},
		{"Name": "pyra2", "Weight": "180"}
    ]
}

#### ================= Find recipe ======================= #
POST {{apiUrl}}/api/findrecipe
authorization: Bearer {{accessToken}}
content-type: application/json

[
    {
        "Name": "2marzec",
        "Weight" : 2
    },
    {
        "Name": "2marzec",
        "Weight" : 2
    }
]







