@apiUrl = http://localhost:5000

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmMjdhZTI0OS1jMjBkLTQ3MTAtYWVmNi1jYWNmMjhiOWNkMTQiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJpYXQiOjE1NTE1MzIxODAsImV4cCI6MTU1MTUzMjQ4MCwidW5pcXVlX25hbWUiOiJmMjdhZTI0OS1jMjBkLTQ3MTAtYWVmNi1jYWNmMjhiOWNkMTQifQ.2rRNcSg-luDkxl9pWAdEopNPC-fjjRVh_lNiP6XI0No

### ================= CREATE USER ======================= #

POST {{apiUrl}}/api/users/register
content-type: application/json

{
    "Login": "2marca",
    "Firstname": "marzec2",
    "Email": "marzec2@op.pl",
    "Password": "2marca"
}

### ================= LOGIN USER ======================= #

POST {{apiUrl}}/api/users/login
content-type: application/json

{
    "Login": "2marca",
    "Password": "2marca"
}

### ================= GET FOOD ITEMS ======================= #

GET {{apiUrl}}/api/FoodItems
authorization: Bearer {{accessToken}}
content-type: application/json


### ================= CREATE FOOD ITEMS ======================= #

POST {{apiUrl}}/api/FoodItems
authorization: Bearer {{accessToken}}
content-type: application/json

{
    "Name": "piwo",
    "Weight": 1,
    "Quantity": 22,
    "CategoryId": 2
}



#### ================= Get all recipes ======================= #

GET {{apiUrl}}/api/Recipes
authorization: Bearer {{accessToken}}
content-type: application/json


#### ================= Get recipe details ======================= #

@recipeGuid = 031c6c40-9bf5-42ac-8722-f8dd0b72e72b

GET {{apiUrl}}/api/Recipes/{{recipeGuid}}
authorization: Bearer {{accessToken}}
content-type: application/json



#### ================= CREATERECIPES ======================= #

POST {{apiUrl}}/api/Recipes
authorization: Bearer {{accessToken}}
content-type: application/json

{
    "Name": "2marzec",
    "Description": "siema marzec",
    "Ingredients": 
	[
		{"Name": "New", "Weight": "150"},
		{"Name": "ziemniak", "Weight": "160"},
		{"Name": "pyra", "Weight": "180"}
    ]
}




