@apiUrl = https://localhost:5001

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NTM2MjYwYi01MjljLTQzZjctOWQ0MC01NDc5YWNhNDk5NzAiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJpYXQiOjE1NTE4MTE3MjAsImV4cCI6MTU1MTgxMjAyMCwidW5pcXVlX25hbWUiOiI1NTM2MjYwYi01MjljLTQzZjctOWQ0MC01NDc5YWNhNDk5NzAifQ.6KJpdA7vgZX0DwkxlcJf4A4N9cDmC7ndTrSTCpSaKFg

### ================= CREATE USER ======================= #

POST {{apiUrl}}/api/users/register
content-type: application/json

{
    "Login": "2marca22",
    "Firstname": "marzec2",
    "Email": "marzec2@op.pl",
    "Password": "2marca22"
}

### ================= LOGIN USER ======================= #

POST {{apiUrl}}/api/users/login
content-type: application/json

{
    "Login": "testt",
    "Password": "test"
}




### ================= GET FOOD ITEMS ======================= #

GET {{apiUrl}}/api/FoodItems
authorization: Bearer {{accessToken}}
content-type: application/json

### ================= GET FOOD ITEM BY ID ======================= #

@userId = C497ED62-3944-4F09-85E0-D99459A841E6
GET {{apiUrl}}/api/FoodItems/{{userId}}
authorization: Bearer {{accessToken}}
content-type: application/json

### ================= CREATE FOOD ITEMS ======================= #

POST {{apiUrl}}/api/FoodItems
authorization: Bearer {{accessToken}}
content-type: application/json

{
    "Name": "piwo222",
    "Weight": 1,
    "Quantity": 22,
    "CategoryId": 2
}

### ================= DELETE FOOD ITEM ======================= #
@foodId = D32F08E7-D830-4A40-91A3-207AB192ED14
DELETE {{apiUrl}}/api/FoodItems
authorization: Bearer {{accessToken}}
content-type: application/json

{
    "Id" : "{{foodId}}"
}







#### ================= Get all recipes ======================= #

GET {{apiUrl}}/api/Recipes
authorization: Bearer {{accessToken}}
content-type: application/json

#### ================= Get recipe details ======================= #

@recipeGuid = e198f1db-4898-4c62-a34a-a182a17ddb9f

GET {{apiUrl}}/api/Recipes/{{recipeGuid}}
authorization: Bearer {{accessToken}}
content-type: application/json

#### ================= CREATE RECIPES ======================= #

POST {{apiUrl}}/api/Recipes
authorization: Bearer {{accessToken}}
content-type: application/json

{
    "Name": "2marzec",
    "Description": "siema marzec",
    "Ingredients": 
	[
		{"Name": "New", "Weight": "150"},
		{"Name": "ziemniak", "Weight": "160"},
		{"Name": "pyra2", "Weight": "180"}
    ]
}

#### ================= Find recipe ======================= #
POST {{apiUrl}}/api/findrecipe
authorization: Bearer {{accessToken}}
content-type: application/json

[
    {
        "Name": "2marzec",
        "Weight" : 2
    },
    {
        "Name": "2marzec",
        "Weight" : 2
    }
]







